version: '3'

services:
    db:
        image: arm64v8/mysql:8.0.32
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: search
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        ports:
            - '3306:3306'
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
